Algoritmo "Depósito"

Var
saldo, deposito, atual: real

Inicio
escreval("Olá, seu saldo atual é de 0, deseja fazer um deposito atráves do boleto ?")
escreva("Digite o valor do depósito:")
leia(deposito)
escreval("Seu boleto foi gerado, o mandaremos pelo email.")
//2 dias depois
escreval("Olá, seu saldo atual é", deposito,".")
escreva("Seu saldo de dois dias atrás era R$ 0, você depositou R$ ", deposito, " e ficou com R$ ", deposito,".")


Fimalgoritmo