Algoritmo "SalarioSE"
VAR nome : CARACTERE;
    salario : REAL;


INICIO
escreva("Digite seu nome: ")
leia(nome)
escreva("Digite seu salário: ")
leia(salario)
se (salario>1200) entao
escreval(nome, " seu salário é maior que o salário mínimo!!!")
senao
se (salario=1200) entao
escreval(nome, " seu salário é igual ao salário mínimo!!!")
senao
escreval(nome, " seu salário é menor que o salário mínimo!!!")
fimse   fimse
fimse


Fimalgoritmo